<?php

namespace GameScoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    public function getByPage($page)
    {
        $query = $this->createQueryBuilder('a')
            ->where('a.lastname LIKE :word')
            ->setParameter('word', $page.'%')
            ->orderBy('a.lastname', 'ASC')
            ->getQuery();

        return new Paginator($query, true);
    }

}


