<?php

namespace GameScoreBundle\Repository;

/**
 * EditorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditorRepository extends \Doctrine\ORM\EntityRepository
{
}
