<?php

namespace GameScoreBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getGames($page)
    {
        $query = $this->createQueryBuilder('g')
            ->where('g.name LIKE :word')
            ->setParameter('word', $page . '%')
            ->orderBy('g.name', 'ASC');

        return new Paginator($query, true);
    }

    public function getAllGames()
    {
        $query = $this->createQueryBuilder('g')
            ->orderBy('g.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }

    public function findByAuthor($author_id)
    {
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare("
            SELECT `id`
            FROM `game`
            INNER JOIN `game_author` ON (`game_author`.`game_id` = `game`.`id`) 
            WHERE `game_author`.`author_id` = :author_id"
        );
        $statement->bindValue('author_id', $author_id);
        $statement->execute();
        $results = $statement->fetchAll();

        return $results;
    }

}
