<?php

namespace GameScoreBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPlayers()
    {
        $query = $this->createQueryBuilder('e')
            ->orderBy('firstname', 'ASC')
            ->getQuery();
        return $query;
    }
}
