<?php

namespace GameScoreBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function getPlayers($page)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.firstname LIKE :word')
            ->setParameter('word', $page.'%')
            ->orderBy('p.firstname', 'ASC')
            ->getQuery();

        return new Paginator($query, true);
    }
}
