<?php

namespace GameScoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayRepository extends EntityRepository
{
    public function findPlayByGame($game)
    {
        $query = $this->createQueryBuilder('play')
            ->where('play.game = :game')
            ->setParameter('game', $game)
            ->orderBy('play.date', 'ASC')
            ->getQuery();
        return $query->getResult();
    }
}
