<?php

namespace GameScoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter;

/**
 * PlayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayRepository extends EntityRepository
{

    // retun array of play id
    public function getPlaysByPlayer($player_id, $limit, $nbPerPage)
    {
        // constructing Limit clause
        if ($nbPerPage) {
            $limitClause = "LIMIT ".$limit.", ".$nbPerPage." ";
        } else {
            $limitClause = "LIMIT ".$limit." ";
        }
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare("
            SELECT play.id
            FROM play
              INNER JOIN score scoreplayer ON (scoreplayer.play_id = play.id)
              INNER JOIN player ON (player.id = scoreplayer.player_id)
            WHERE scoreplayer.player_id = :player_id
            GROUP BY play.id
            ORDER BY play.date DESC "
            . $limitClause
        );
        $statement->bindValue('player_id', $player_id);
        $statement->execute();
        $results = $statement->fetchAll();
        return $results;
    }

    public function getPlaysByGame($game_id, $limit, $nbPerPage)
    {
        // constructing Limit clause
        if ($nbPerPage) {
            $limitClause = "LIMIT ".$limit.", ".$nbPerPage." ";
        } else {
            $limitClause = "LIMIT ".$limit." ";
        }
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare("
            SELECT play.id
            FROM play
            WHERE game_id = :game_id
            ORDER BY play.date DESC "
            . $limitClause
        );
        $statement->bindValue('game_id', $game_id);
        $statement->execute();
        $results = $statement->fetchAll();
        return $results;
    }

}
