game_score:
  resource: "@GameScoreBundle/Resources/config/routing.yml"
  prefix:   /

app:
  resource: '@AppBundle/Controller/'
  type: annotation

# login ~ logout routes
login:
  path: /login
  defaults:
    _controller: UserBundle:Security:login

login_check:
  path: /login_check

logout:
  path: /logout