# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
      #Symfony\Component\Security\Core\User\User: plaintext
      UserBundle\Entity\User: sha512

    role_hierarchy:
      ROLE_ADMIN:         ROLE_USER
      ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
          id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # this firewall only to give access to everyone to the login form
        main_login:
            pattern: ^/login$
            anonymous: true
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: login
            remember_me:
                secret: %secret%

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANNYMOUSLY, requires_channel: https }
