# Route for home
game_score_homepage:
    path:     /
    methods: GET
    defaults:
        _controller: GameScoreBundle:GameScore:index

# Route for stats
game_score_stats_homepage:
    path:     /stats
    methods: GET
    defaults:
        _controller: GameScoreBundle:Stats:index

# Routes for Games
game_score_game_view:
    path:     /game/{id}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Game:view
        requirements:
            id: \d+

game_score_game_collection:
    path:     /games/{page}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Game:collection

game_score_game_create:
    path:     /game/create/
    methods: GET
    defaults:
        _controller: GameScoreBundle:Game:create

game_score_game_update:
    path:     /game/update/{id}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Game:update
    requirements:
        id: \d+

# Routes for Editors
game_score_editor_view:
    path:     /editor/{id}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Editor:view
        requirements:
            id: \d+

game_score_editor_collection:
    path:     /editors/{page}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Editor:collection
    requirements:
        page: \d+

game_score_editor_create:
    path:     /editor/create/
    methods: GET
    defaults:
        _controller: GameScoreBundle:Editor:create

game_score_editor_update:
    path:     /editor/update/{id}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Editor:update
    requirements:
        id: \d+

# Routes for Authors
game_score_author_view:
    path:     /author/{id}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Author:view
    requirements:
        id: \d+

game_score_author_collection:
    path:     /authors/{page}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Author:collection

game_score_author_create:
    path:     /author/create/
    methods: GET
    defaults:
        _controller: GameScoreBundle:Author:create

game_score_author_update:
    path:     /author/update/{id}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Author:update
        requirements:
          id: \d+

# Routes for Players
game_score_player_view:
    path:     /player/{id}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Player:view
        requirements:
            id: \d+

game_score_player_mostplayedgamesview:
    path:     /player/{id}/mostplayedgames/
    methods: GET
    defaults:
        _controller: GameScoreBundle:Player:mostPlayedGamesView
        requirements:
            id: \d+

game_score_player_collection:
    path:     /players/{page}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Player:collection

game_score_player_create:
    path:     /player/create/
    methods: GET
    defaults:
        _controller: GameScoreBundle:Player:create

game_score_player_update:
    path:     /player/update/{id}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Player:update
    requirements:
        id: \d+

# Routes for plays
game_score_play_view:
    path:     /play/{id}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Play:view
        requirements:
            id: \d+

game_score_play_create:
    path:     /play/create/
    methods: GET
    defaults:
        _controller: GameScoreBundle:Play:create

game_score_play_update:
    path: /play/update/{id}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Play:update
    requirements:
        id: \d+

# Routes for scores
game_score_score_create:
    path: /play/{id}/score/create/
    methods: GET
    defaults:
        _controller: GameScoreBundle:Score:create
    requirements:
        id: \d+

game_score_score_update:
    path: /score/update/{id}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Score:update
    requirements:
        id: \d+

game_score_score_delete:
    path: /score/delete/{id}
    methods: GET
    defaults:
        _controller: GameScoreBundle:Score:delete
    requirements:
        id: \d+

# Routes for documents
game_score_document_upload:
    path: /document/upload/{entitytype}/{entityid}
    methods: GET
    defaults: {_controller: GameScoreBundle:Document:upload, entitytype: 'common', entityid: 1}
