game_score_homepage:
    path:     /
    defaults: { _controller: GameScoreBundle:Default:index }

game_score_view_game_card:
    path:     /gamecard/view/{game_id}
    defaults:
        _controller: GameScoreBundle:Game:viewGameCard
        requirements:
            game_id: \d+

game_score_create_game_card:
    path:     /gamecard/create/
    defaults:
        _controller: GameScoreBundle:Game:createGameCard


