game_score_homepage:
    path:     /
    defaults: { _controller: GameScoreBundle:GameScore:index }

# Routes for Games

game_score_game_collection:
    path:     /game/collection/{page}
    defaults:
        _controller: GameScoreBundle:Game:gameCollection


game_score_create_game:
    path:     /game/create/
    defaults:
        _controller: GameScoreBundle:Game:createGame

game_score_update_game:
    path:     /game/update/{game_id}
    defaults:
        _controller: GameScoreBundle:Game:updateGame
        requirements:
          game_id: \d+

game_score_view_game:
    path:     /game/view/{game_id}
    defaults:
        _controller: GameScoreBundle:Game:readGame
        requirements:
            game_id: \d+

# Routes for Editors

game_score_editor_collection:
    path:     /editor/collection/{page}
    defaults:
        _controller: GameScoreBundle:Editor:editorCollection
    requirements:
        page: \d+


game_score_create_editor:
    path:     /editor/create/
    defaults:
        _controller: GameScoreBundle:Editor:createEditor

game_score_update_editor:
    path:     /editor/update/{editor_id}
    defaults:
        _controller: GameScoreBundle:Editor:updateEditor
        requirements:
          editor_id: \d+

game_score_view_editor:
    path:     /editor/view/{editor_id}
    defaults:
        _controller: GameScoreBundle:Editor:readEditor
        requirements:
            editor_id: \d+

# Routes for Authors

game_score_author_collection:
    path:     /author/collection/
    defaults:
        _controller: GameScoreBundle:Author:authorCollection

game_score_create_author:
    path:     /author/create/
    defaults:
        _controller: GameScoreBundle:Author:createAuthor

game_score_update_author:
    path:     /author/update/{author_id}
    defaults:
        _controller: GameScoreBundle:Author:updateAuthor
        requirements:
          author_id: \d+

game_score_view_author:
    path:     /author/view/{author_id}
    defaults:
        _controller: GameScoreBundle:Author:readAuthor
        requirements:
            author_id: \d+

# Routes for Players

game_score_player_collection:
    path:     /player/collection/{page}
    defaults:
        _controller: GameScoreBundle:Player:collection

game_score_create_player:
    path:     /player/create/
    defaults:
        _controller: GameScoreBundle:Player:create

game_score_update_player:
    path:     /player/update/{player_id}
    defaults:
        _controller: GameScoreBundle:Player:update
    requirements:
        player_id: \d+

game_score_view_player:
    path:     /player/view/{player_id}/{page}
    defaults:
        _controller: GameScoreBundle:Player:view
        page: 1
        requirements:
            player_id: \d+

# Routes for plays

game_score_view_play:
    path:     /play/view/{play_id}
    defaults:
        _controller: GameScoreBundle:Play:view
        requirements:
            player_id: \d+