game_score_homepage:
    path:     /
    defaults: { _controller: GameScoreBundle:GameScore:index }

# Routes for Games
game_score_game_view:
    path:     /game/view/{game_id}
    defaults:
        _controller: GameScoreBundle:Game:readGame
        requirements:
            game_id: \d+

game_score_game_collection:
    path:     /game/collection/{page}
    defaults:
        _controller: GameScoreBundle:Game:gameCollection

game_score_game_create:
    path:     /game/create/
    defaults:
        _controller: GameScoreBundle:Game:createGame

game_score_game_update:
    path:     /game/update/{game_id}
    defaults:
        _controller: GameScoreBundle:Game:updateGame
        requirements:
          game_id: \d+

# Routes for Editors
game_score_editor_view:
    path:     /editor/view/{id}
    defaults:
        _controller: GameScoreBundle:Editor:view
        requirements:
            id: \d+

game_score_editor_collection:
    path:     /editor/collection/{page}
    defaults:
        _controller: GameScoreBundle:Editor:collection
    requirements:
        page: \d+

game_score_editor_create:
    path:     /editor/create/
    defaults:
        _controller: GameScoreBundle:Editor:createEditor

game_score_editor_update:
    path:     /editor/update/{id}
    defaults:
        _controller: GameScoreBundle:Editor:updateEditor
        requirements:
          id: \d+

# Routes for Authors
game_score_view_author:
    path:     /author/view/{author_id}
    defaults:
        _controller: GameScoreBundle:Author:readAuthor
        requirements:
            author_id: \d+

game_score_author_collection:
    path:     /author/collection/
    defaults:
        _controller: GameScoreBundle:Author:authorCollection

game_score_author_create:
    path:     /author/create/
    defaults:
        _controller: GameScoreBundle:Author:createAuthor

game_score_author_update:
    path:     /author/update/{author_id}
    defaults:
        _controller: GameScoreBundle:Author:updateAuthor
        requirements:
          author_id: \d+

# Routes for Players

game_score_player_collection:
    path:     /player/collection/{page}
    defaults:
        _controller: GameScoreBundle:Player:collection

game_score_create_player:
    path:     /player/create/
    defaults:
        _controller: GameScoreBundle:Player:create

game_score_update_player:
    path:     /player/update/{player_id}
    defaults:
        _controller: GameScoreBundle:Player:update
    requirements:
        player_id: \d+

game_score_view_player:
    path:     /player/view/{player_id}/{page}
    defaults:
        _controller: GameScoreBundle:Player:view
        page: 1
        requirements:
            player_id: \d+

# Routes for plays

game_score_view_play:
    path:     /play/view/{play_id}
    defaults:
        _controller: GameScoreBundle:Play:view
        requirements:
            player_id: \d+