game_score_homepage:
    path:     /
    defaults: { _controller: GameScoreBundle:GameScore:index }

# Routes for Games
game_score_game_view:
    path:     /game/view/{game_id}
    defaults:
        _controller: GameScoreBundle:Game:readGame
        requirements:
            game_id: \d+

game_score_game_collection:
    path:     /game/collection/{page}
    defaults:
        _controller: GameScoreBundle:Game:gameCollection

game_score_game_create:
    path:     /game/create/
    defaults:
        _controller: GameScoreBundle:Game:createGame

game_score_game_update:
    path:     /game/update/{game_id}
    defaults:
        _controller: GameScoreBundle:Game:updateGame
        requirements:
          game_id: \d+

# Routes for Editors
game_score_editor_view:
    path:     /editor/view/{id}
    defaults:
        _controller: GameScoreBundle:Editor:view
        requirements:
            id: \d+

game_score_editor_collection:
    path:     /editor/collection/{page}
    defaults:
        _controller: GameScoreBundle:Editor:collection
    requirements:
        page: \d+

game_score_editor_create:
    path:     /editor/create/
    defaults:
        _controller: GameScoreBundle:Editor:create

game_score_editor_update:
    path:     /editor/update/{id}
    defaults:
        _controller: GameScoreBundle:Editor:update
    requirements:
        id: \d+

# Routes for Authors
game_score_author_view:
    path:     /author/view/{author_id}
    defaults:
        _controller: GameScoreBundle:Author:view
        requirements:
            author_id: \d+

game_score_author_collection:
    path:     /author/collection/
    defaults:
        _controller: GameScoreBundle:Author:collection

game_score_author_create:
    path:     /author/create/
    defaults:
        _controller: GameScoreBundle:Author:create

game_score_author_update:
    path:     /author/update/{author_id}
    defaults:
        _controller: GameScoreBundle:Author:update
        requirements:
          author_id: \d+

# Routes for Players
game_score_player_view:
    path:     /player/view/{id}/{page}
    defaults:
        _controller: GameScoreBundle:Player:view
        page: 1
        requirements:
            id: \d+

game_score_player_collection:
    path:     /player/collection/{page}
    defaults:
        _controller: GameScoreBundle:Player:collection

game_score_player_create:
    path:     /player/create/
    defaults:
        _controller: GameScoreBundle:Player:create

game_score_player_update:
    path:     /player/update/{player_id}
    defaults:
        _controller: GameScoreBundle:Player:update
    requirements:
        player_id: \d+

# Routes for plays
game_score_play_view:
    path:     /play/{id}
    defaults:
        _controller: GameScoreBundle:Play:view
    requirements:
        id: \d+

game_score_play_create:
    path:     /play/create/
    defaults:
        _controller: GameScoreBundle:Play:create

# Routes for scores
game_score_score_create:
    path: /play/{id}/score/create/
    defaults:
        _controller: GameScoreBundle:Score:Create
    requirements:
            player_id: \d+