services:

  helper_service:
      class: GameScoreBundle\Service\HelperService
      arguments:

  game_service:
    class: GameScoreBundle\Service\GameService
    arguments:
      - "@doctrine.orm.entity_manager"

  document_service:
    class: GameScoreBundle\Service\DocumentService
    arguments:
      - "@doctrine.orm.entity_manager"

  play_service:
    class: GameScoreBundle\Service\PlayService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@service_container"

  alphabetical_pagination:
    class: GameScoreBundle\Service\AlphabeticalPagination
    arguments:
      - "@doctrine.orm.entity_manager"

  alphabeta_html_adder:
    class: GameScoreBundle\Service\AlphaBetaHTMLAdder
    arguments:
      - "@service_container"

  load_page_log_writer:
      class: GameScoreBundle\Service\LoadPageLogWriter
      arguments:
        - "@service_container"

  # Listeners

  alphabeta_listener:
    class: GameScoreBundle\Listener\AlphaBetaListener
    arguments:
      - "@alphabeta_html_adder"
      - "2016-01-01"
    tags:
      - {name: kernel.event_listener, event: kernel.response, method: processBeta}

  loadpage_listener:
      class: GameScoreBundle\Listener\LoadPageListener
      arguments:
        - "@load_page_log_writer"
      tags:
        - {name: kernel.event_listener, event: GameScore.home_page_load, method: onLoadProcess}

#    game_score.example:
#        class: GameScoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
