services:
  service_game:
    class: GameScoreBundle\Service\ServiceGame
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@service_container"

#    game_score.example:
#        class: GameScoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
