services:
  game_score_get_number_of_games:
    class: GameScoreBundle\Controller\GameController
    arguments:
      - "@doctrine.orm.entity_manager"

#    game_score.example:
#        class: GameScoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
