services:

  game_service:
    class: GameScoreBundle\Service\GameService
    arguments:
      - "@doctrine.orm.entity_manager"

  document_service:
    class: GameScoreBundle\Service\DocumentService
    arguments:
      - "@doctrine.orm.entity_manager"

  play_service:
    class: GameScoreBundle\Service\PlayService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@service_container"

  alphabetical_pagination:
    class: GameScoreBundle\Service\AlphabeticalPagination
    arguments:
      - "@doctrine.orm.entity_manager"

  alphabeta_html_adder:
    class: GameScoreBundle\Service\AlphaBetaHTMLAdder
    arguments:
      - "@service_container"

  alphabeta_listener:
    class: GameScoreBundle\Listener\AlphaBetaListener
    arguments:
      - "@alphabeta_html_adder"
      - "2016-01-01"
    tags:
      - {name: kernel.event_listener, event: kernel.response, method: processBeta}



#    game_score.example:
#        class: GameScoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
