user_view:
    path:     /user/view/{id}
    defaults:
        _controller: UserBundle:User:view
    requirements:
        id: \d+

user_update:
    path:     /user/update/{id}
    defaults:
        _controller: UserBundle:User:update
    requirements:
        id: \d+

user_collection:
    path:     /user/collection/
    defaults:
        _controller: UserBundle:User:collection
